version: '3'
services:

  eureka-server:
    build: ./mServer
    restart: always
    ports:
      - "8761:8761"

  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mongodb:
    image : mongo
    restart: always

  patient:
    build: ./mPatient
    restart: always
    depends_on:
      - eureka-server
      - mysqldb
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_PASSWORD}
      - spring.profiles.active=prod
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

  notes:
    build: ./mNotes
    restart: always
    depends_on:
      - eureka-server
      - mongodb
    ports:
      - "8082:8082"
    environment:
      - spring.data.mongodb.database=${MONGO_DATABASE}
      - spring.data.mongodb.host=mongodb
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

  assessment:
    build: ./mAssessment
    restart: always
    depends_on:
      - eureka-server
      - mongodb
      - patient
    ports:
      - "8083:8083"
    environment:
      - spring.data.mongodb.database=${MONGO_DATABASE}
      - spring.data.mongodb.host=mongodb
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

  mediscreen-ui:
    build: ./ui/mediscreen-ui
    ports:
      - "4200:80"

  authentication:
    build: ./mAuthentication
    restart: always
    depends_on:
      - eureka-server
      - mysqldb
    ports:
      - "8085:8085"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_PASSWORD}
      - spring.profiles.active=prod
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

  gateway:
    build: ./mGateway
    restart: always
    depends_on:
      - eureka-server
      - patient
      - authentication
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/