
DELETE FROM `patient`;

INSERT INTO `patient` (`address`, `birthdate`, `first_name`, `last_name`, `phone`)
VALUES
    (UUID(), CURRENT_DATE - INTERVAL FLOOR(RAND() * 80) YEAR, UUID(), UUID() , UUID()),
    (UUID(), CURRENT_DATE - INTERVAL FLOOR(RAND() * 80) YEAR, UUID(), UUID() , UUID()),
    (UUID(), CURRENT_DATE - INTERVAL FLOOR(RAND() * 80) YEAR, UUID(), UUID() , UUID()),
    (UUID(), CURRENT_DATE - INTERVAL FLOOR(RAND() * 80) YEAR, UUID(), UUID() , UUID()),
    (UUID(), CURRENT_DATE - INTERVAL FLOOR(RAND() * 80) YEAR, UUID(), UUID() , UUID()),
    (UUID(), CURRENT_DATE - INTERVAL FLOOR(RAND() * 80) YEAR, UUID(), UUID() , UUID()),
    (UUID(), CURRENT_DATE - INTERVAL FLOOR(RAND() * 80) YEAR, UUID(), UUID() , UUID()),
    (UUID(), CURRENT_DATE - INTERVAL FLOOR(RAND() * 80) YEAR, UUID(), UUID() , UUID()),
    (UUID(), CURRENT_DATE - INTERVAL FLOOR(RAND() * 80) YEAR, UUID(), UUID() , UUID()),
    (UUID(), CURRENT_DATE - INTERVAL FLOOR(RAND() * 80) YEAR, UUID(), UUID() , UUID());

